BiluthyrningAB/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BiluthyrningAB.Data;
using BiluthyrningAB.Models;
using BiluthyrningAB.ViewModels;
using BiluthyrningAB.Persistence.Repositories;

namespace BiluthyrningAB.Controllers
{
    public class BookingsController : Controller
    {
        private readonly IBookingRepository _bookingRepository;
        private readonly ICarRepository _carRepository;
        private readonly ICustomerRepository _customerRepository;
        private readonly IEntityFrameworkRepository _entityFrameworkRepository;

        public BookingsController(IBookingRepository bookingRepository, ICarRepository carRepository, IEntityFrameworkRepository entityFrameworkRepository, ICustomerRepository customerRepository)
        {
            _bookingRepository = bookingRepository;
            _carRepository = carRepository;
            _entityFrameworkRepository = entityFrameworkRepository;
            _customerRepository = customerRepository;
        }


        public async Task<IActionResult> Index()
        {
            var myTask = Task.Run(() => _bookingRepository.GetAllBookings());
            return View(await myTask);
        }


        public async Task<IActionResult> BookingsForCertainCustomer(Guid? CustomerId)
        {
            var myTask = Task.Run(() => _bookingRepository.GetBookingsForCertainCustomer(CustomerId));
            return View(await myTask);
        }


        public async Task<IActionResult> OnGoingBookings()
        {
            var myTask = Task.Run(() => _bookingRepository.GetBookingsDependingOnStatus(true));
            return View(await myTask);
        }


        public async Task<IActionResult> Not_OnGoingBookings()
        {
            var myTask = Task.Run(() => _bookingRepository.GetBookingsDependingOnStatus(false));
            return View(await myTask);
        }


        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var booking = _bookingRepository.GetBookingById(id);

            if (booking == null)
                return NotFound();

            return View(booking);
        }


        public IActionResult Create()
        {
            BookingVm bookingVm = new BookingVm();

            //Fyller listan med bilarna som finns genom metod
            bookingVm.Cars = FillCarListOfSelectListItems();

            //Fyller listan med kunder som finns genom metod
            bookingVm.Customers = FillCustomerListOfSelectListItems();

            return View(bookingVm);
        }


        public List<SelectListItem> FillCustomerListOfSelectListItems()
        {
            var customers = _customerRepository.GetAllCustomers();

            List<SelectListItem> listOfCustomers = new List<SelectListItem>();

            foreach (var customer in customers)
            {
                string wholeName = $"{customer.FirstName} {customer.LastName}";
                var x = new SelectListItem() { Text = wholeName, Value = customer.CustomerId.ToString() };
                listOfCustomers.Add(x);
            }
            return listOfCustomers;
        }


        public List<SelectListItem> FillCarListOfSelectListItems()
        {
            var cars = _carRepository.GetAllCars();

            List<SelectListItem> listOfCars = new List<SelectListItem>();

            foreach (var car in cars)
            {
                var y = new SelectListItem() { Text = car.LicenseNumber, Value = car.CarId.ToString(), Group = new SelectListGroup { Name = car.CarType.ToString() } };
                listOfCars.Add(y);
            }

            return listOfCars;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingId,CustomerId,CarId,StartDate")] Booking booking)
        {
            booking.ReturnDate = booking.StartDate.AddDays(1);
            booking.OnGoing = true;

            //Hämtar bilen vi har att göra med och sätter den till bokad. Om den redan är bokad så berättar vi det 
            booking.Car = _carRepository.GetCarById(booking.CarId);


            if (booking.Car.Booked == false)
            {
                booking.Car.Booked = true;
            }
            else
            {
                ViewBag.Message = "Bilen är redan bokad, vänligen välj en annan";
                BookingVm error_bookingVm = new BookingVm();
                error_bookingVm.Cars = FillCarListOfSelectListItems();
                error_bookingVm.Customers = FillCustomerListOfSelectListItems();
                return View(error_bookingVm);
            }

            if (ModelState.IsValid)
            {
                //Lägger till bokningen i systemet
                booking.BookingId = Guid.NewGuid();
                _bookingRepository.AddBooking(booking);

                //Uppdaterar bilen till bokad
                _carRepository.UpdateCar(booking.Car);

                _entityFrameworkRepository.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            BookingVm bookingVm = new BookingVm();

            //Om det misslyckas så hämtar vi bilarna på nytt
            bookingVm.Cars = FillCarListOfSelectListItems();

            ////Om det misslyckas så hämtar vi kunderna på nytt
            bookingVm.Customers = FillCustomerListOfSelectListItems();

            return View(bookingVm);
        }


        public async Task<IActionResult> FinishBooking(Guid? id)
        {
            if (id == null)
                return NotFound();

            var booking = _bookingRepository.GetBookingById(id);

            if (booking == null)
                return NotFound();

            return View(booking);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FinishBooking(Guid id, [Bind("BookingId,NumberOfKm,StartDate,ReturnDate,CustomerId,Car")] Booking booking)
        {
            if (id != booking.BookingId)
                return NotFound();

            if (booking.Price < 0)
            {
                ViewBag.Message = "Nu blev det något galet med antalet körda kilometer eller datumen, återlämningsdatum måste vara senare än inlämningsdatum";
                return View(booking);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Sätter ordern till slutförd
                    booking.OnGoing = false;

                    //Gör bilen obokad igen
                    booking.Car.Booked = false;

                    //uppdaterar bilens antal körda kilometer
                    booking.Car.NumberOfDrivenKm = booking.Car.NumberOfDrivenKm + Convert.ToInt32(booking.NumberOfKm);

                    //Uppdaterar sedan både bilen (för antalet mils räkning) samt bokningen
                    _carRepository.UpdateCar(booking.Car);
                    _bookingRepository.UpdateBooking(booking);

                    _entityFrameworkRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }


        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var booking = _bookingRepository.GetBookingById(id);

            if (booking == null)
                return NotFound();

            return View(booking);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("BookingId,NumberOfKm,StartDate,ReturnDate,OnGoing,CarId,CustomerId,Car")] Booking booking)
        {
            if (id != booking.BookingId)
                return NotFound();

            if (booking.Price < 0)
            {
                ViewBag.Message = "Nu blev det något galet med antalet körda kilometer eller datumen, återlämningsdatum måste vara senare än inlämningsdatum";
                return View(booking);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _bookingRepository.UpdateBooking(booking);
                    _entityFrameworkRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }


        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var booking = _bookingRepository.GetBookingById(id);

            if (booking == null)
                return NotFound();

            return View(booking);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var booking = _bookingRepository.GetBookingById(id);
            _bookingRepository.RemoveBooking(booking);
            _entityFrameworkRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool BookingExists(Guid id)
        {

BiluthyrningAB/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BiluthyrningAB.Data;
using BiluthyrningAB.Models;
using BiluthyrningAB.Persistence.Repositories;

namespace BiluthyrningAB.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IEntityFrameworkRepository _entityFrameworkRepository;

        public CustomersController(ICustomerRepository customerRepository, IEntityFrameworkRepository entityFrameworkRepository)
        {
            _customerRepository = customerRepository;
            _entityFrameworkRepository = entityFrameworkRepository;
        }


        public async Task<IActionResult> Index()
        {
            var myTask = Task.Run(() => _customerRepository.GetAllCustomers());
            return View(await myTask);
        }


        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var customer = _customerRepository.GetCustomerById(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,PersonNumber,FirstName,LastName")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.CustomerId = Guid.NewGuid();
                _customerRepository.AddCustomer(customer);

                _entityFrameworkRepository.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }


        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var customer = _customerRepository.GetCustomerById(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CustomerId,PersonNumber,FirstName,LastName")] Customer customer)
        {
            if (id != customer.CustomerId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _customerRepository.UpdateCustomer(customer);

                    _entityFrameworkRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }


        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var customer = _customerRepository.GetCustomerById(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var customer = _customerRepository.GetCustomerById(id);
            _customerRepository.RemoveCustomer(customer);

            _entityFrameworkRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool CustomerExists(Guid id)
        {
            return _customerRepository.CustomerExists(id);
        }
    }
}

BiluthyrningAB/Views/Customers/Create.cshtml
@model BiluthyrningAB.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h4>Lägg till kund</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonNumber" class="control-label"></label>
                <input asp-for="PersonNumber" class="form-control" />
                <span asp-validation-for="PersonNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lägg till" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Gå tillbaka</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BiluthyrningAB/Views/Customers/Delete.cshtml
@model BiluthyrningAB.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h3>Är du säker på att du vill ta bort kunden?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PersonNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerId" />
        <input type="submit" value="Ta bort" class="btn btn-primary" /> |
        <a asp-action="Index">Gå tillbaka</a>
    </form>
</div>

BiluthyrningAB/Views/Customers/Details.cshtml
@model BiluthyrningAB.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Detaljer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PersonNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CustomerId">Ändra</a> |
    <a asp-action="Index">Gå tillbaka</a>
</div>

BiluthyrningAB/Views/Customers/Edit.cshtml
@model BiluthyrningAB.Models.Customer

@{
    ViewData["Title"] = "Edit";
}

<h4>Ändra kund</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="PersonNumber" class="control-label"></label>
                <input asp-for="PersonNumber" class="form-control" />
                <span asp-validation-for="PersonNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Gå tillbaka</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BiluthyrningAB/Views/Customers/Index.cshtml
@model IEnumerable<BiluthyrningAB.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create" class="btn btn-primary">Lägg till kund</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Kundnummer
                @{ int count = 1;}
            </th>
            <th>
                Namn
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonNumber)
            </th>
            <th></th>
            <th>
                Bokningar
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @count
                @{ count++;}
            </td>
            <td>
                @item.FirstName @item.LastName
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CustomerId" class="btn btn-outline-info">Ändra</a>
                <a asp-action="Details" asp-route-id="@item.CustomerId" class="btn btn-outline-info">Detaljer</a>
                <a asp-action="Delete" asp-route-id="@item.CustomerId" class="btn btn-outline-info">Ta bort</a>
            </td>
            <td>
                <a asp-controller="Bookings" asp-action="BookingsForCertainCustomer" asp-route-CustomerId="@item.CustomerId" class="btn btn-primary">Bokningar</a>
            </td>
        </tr>
}
    </tbody>
</table>